import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { Dela_Gothic_One } from "next/font/google";
import '@/assets/scss/general.scss'

// const Dela_Gothic_OneSans = Dela_Gothic_One({
//   variable: "--font-Dela_Gothic_One-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <body>
        {children}
      </body>
    </html>
  );
}
